# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Tom Martin

description: Stylish Jekyll Theme
author:
  name: Tom Martin
  email: tpgmartin@gmail.com
  github: tpgmartin
  twitter: tpgmartin
  pinterest: 
  linkedin: thomas-martin
  bio: Junior developer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
