# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "jekyll.thor"] # files to exclude
highlighter: pygments
markdown: kramdown
permalink: pretty

defaults:
  scope:
  path: "" # empty string for all files
  values:
  title: tpgmartin.com

description: A blog on programming and things
author:
  name: Tom Martin
  twitter: tpgmartin
  google-plus: 112326764922237690846
  facebook: tpgmartin
  email: tom@tpgmartin.com
  github: tpgmartin
  linkedin: tpgmartin
  stack-overflow: 3680722/tpgmartin
  youtube: UCYRrmC7_3CUm-scefheGfnQ
  instagram: tpgmartin
  pinterest: tpgmartin
  bio: Junior developer, London, UK
  email_md5: 62be213366aa2bdd663069b3a0cfaf72

gems:
  - jekyll-sitemap

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

bitly:
  username: tpgmartin
  api_key: R_b3ee105c6fe74ae3895298489c72c468

rss_path: feed.xml
cv_path: tom-martin-cv.pdf
about_path: about
categories_path: categories
tags_path: tags

BASE_PATH:
